spring:
 datasource:
   url: jdbc:postgresql://localhost:5432/fineract_default
   driver-class-name: org.postgresql.Driver
   username: postgres
   password: postgres
server:
  port: 9090
  servlet:
    context-path: /mifos